<?xml version="1.0"?>
<package format="3">
  <name>quadropted_perception</name>
  <version>0.1.0</version>
  <description>YOLO object detection for quadruped robot simulation</description>

  <maintainer email="boss6852@gmail.com">RedAlexDad</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>vision_msgs</depend>
  <depend>quadropted_msgs</depend>
  <depend>cv_bridge</depend>

  <exec_depend>ultralytics</exec_depend>
  <exec_depend>torch</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
