# makefiles/help.mk

.PHONY: help

## Показать справку
help:
	@echo ""
	@printf "${CYAN}${BOLD}╔════════════════════════════════════════════════════════════╗${NC}\n"
	@printf "${CYAN}${BOLD}║${NC}  Walking Robot Simulation Manager v3.0                     ${CYAN}${BOLD}║${NC}\n"
	@printf "${CYAN}${BOLD}╚════════════════════════════════════════════════════════════╝${NC}\n"
	@echo ""
	@printf "${BOLD}Основные команды:${NC}\n"
	@printf "  ${GREEN}${BOLD}make deploy${NC}         Сборка и запуск (рекомендуется)\n"
	@printf "  ${GREEN}${BOLD}make build${NC}          Сборка Docker образа\n"
	@printf "  ${GREEN}${BOLD}make up${NC}             Запуск контейнера\n"
	@printf "  ${GREEN}${BOLD}make down${NC}           Остановка контейнера\n"
	@printf "  ${GREEN}${BOLD}make shell${NC}          Подключение к контейнеру\n"
	@printf "  ${GREEN}${BOLD}make logs${NC}           Просмотр логов\n"
	@echo ""
	@printf "${BOLD}Симуляция:${NC}\n"
	@printf "  ${GREEN}${BOLD}make gazebo${NC}         Запуск Gazebo симуляции (C++)\n"
	@printf "  ${GREEN}${BOLD}make gazebo-py${NC}      Запуск Gazebo симуляции (Python)\n"
	@printf "  ${GREEN}${BOLD}make gazebo-cpp${NC}     Запуск Gazebo симуляции (C++)\n"
	@printf "  ${GREEN}${BOLD}make teleop${NC}         Запуск управления роботом\n"
	@printf "  ${GREEN}${BOLD}make kill-ros${NC}       Очистка всех ROS/Gazebo процессов\n"
	@echo ""
	@printf "${BOLD}Состояния робота:${NC}\n"
	@printf "  ${GREEN}${BOLD}make rest${NC}           Режим отдыха (REST)\n"
	@printf "  ${GREEN}${BOLD}make stand${NC}          Режим стойки (STAND)\n"
	@printf "  ${GREEN}${BOLD}make trot${NC}           Режим бега рысью (TROT)\n"
	@printf "  ${GREEN}${BOLD}make crawl${NC}          Режим ползания (CRAWL)\n"
	@echo ""
	@printf "${BOLD}Waypoint навигация:${NC}\n"
	@printf "  ${GREEN}${BOLD}make waypoint-start${NC}               Запуск навигации по всем waypoints\n"
	@printf "  ${GREEN}${BOLD}make waypoint-navigate INDEX=2${NC}    Навигация к конкретному waypoint\n"
	@printf "  ${GREEN}${BOLD}make waypoint-stop${NC}                Остановка текущей навигации\n"
	@printf "  ${GREEN}${BOLD}make waypoint-resume${NC}              Продолжить навигацию\n"
	@printf "  ${GREEN}${BOLD}make waypoint-load FILE=wp.yaml${NC}   Загрузить waypoints из файла\n"
	@printf "  ${GREEN}${BOLD}make waypoint-get${NC}                 Получить текущие waypoints\n"
	@printf "  ${GREEN}${BOLD}make waypoint-clear${NC}               Очистка waypoints\n"
	@printf "  ${BOLD}  --- Эксперименты ---${NC}\n"
	@printf "  ${GREEN}${BOLD}make experiment-start${NC}            Запустить замер времени/дистанции\n"
	@printf "  ${GREEN}${BOLD}make experiment-stop${NC}             Остановить и сохранить результат\n"
	@printf "  ${GREEN}${BOLD}make experiment-result${NC}           Показать путь к файлу с результатами\n"
	@echo ""
	@printf "${BOLD}YOLO:${NC}\n"
	@printf "  ${GREEN}${BOLD}make yolo-detector${NC}                        Запуск YOLO детектора\n"
	@printf "  ${GREEN}${BOLD}make yolo-visualizer${NC}                    Визуализация детекций в RViz\n"
	@printf "  ${BOLD}  --- Эксперименты ---${NC}\n"
	@printf "  ${GREEN}${BOLD}make yolo-experiment-start LOG_INTERVAL=10${NC}  Запуск YOLO эксперимента (фон)\n"
	@printf "  ${GREEN}${BOLD}make yolo-experiment-stop${NC}               Остановка YOLO эксперимента\n"
	@printf "  ${GREEN}${BOLD}make yolo-experiment-result${NC}             Копировать лог YOLO на хост\n"
	@echo ""
	@printf "${BOLD}Положение робота:${NC}\n"
	@printf "  ${GREEN}${BOLD}make set-pose X=1.0 Y=0.0 Z=0.0 YAW=0.0${NC}   Установка положения\n"
	@printf "  ${GREEN}${BOLD}make reset-pose${NC}                           Сброс положения\n"
	@echo ""
	@printf "${BOLD}Сборка по этапам:${NC}\n"
	@printf "  ${GREEN}${BOLD}make build-stage STAGE=ros-core${NC}   Сборка конкретного этапа\n"
	@printf "  ${GREEN}${BOLD}make build-stage-list${NC}             Показать доступные этапы\n"
	@echo ""
	@printf "${BOLD}Тестирование и CI:${NC}\n"
	@printf "  ${GREEN}${BOLD}make test${NC}                 Полный цикл тестирования\n"
	@printf "  ${GREEN}${BOLD}make test-correctness${NC}     Тесты корректности Python\n"
	@printf "  ${GREEN}${BOLD}make benchmark${NC}            Бенчмарк Python + C++\n"
	@printf "  ${GREEN}${BOLD}make ci-lint${NC}              Линтинг всех языков\n"
	@printf "  ${GREEN}${BOLD}make ci-test-cpp${NC}          C++ unit тесты\n"

	@printf "${BOLD}Прочее:${NC}\n"
	@printf "  ${GREEN}${BOLD}make exec CMD='ros2 topic list'${NC}   Выполнение команды\n"
	@printf "  ${GREEN}${BOLD}make setup${NC}                        Начальная настройка\n"
	@printf "  ${GREEN}${BOLD}make save-logs${NC}                    Сохранение логов\n"
	@printf "  ${GREEN}${BOLD}make clean${NC}                        Полная очистка Docker\n"
	@printf "  ${GREEN}${BOLD}make help${NC}                         Эта справка\n"
	@echo ""
	@printf "${BOLD}Технологии:${NC}\n"
	@printf "  ROS 2 ${BOLD}$(ROS_DISTRO)${NC}\n"
	@printf "  Gazebo Harmonic\n"
	@printf "  Docker + Docker Compose\n"
	@echo ""
