cmake_minimum_required(VERSION 3.8)
project(gazebo_sim)

if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
  add_compile_options(-Wall -Wextra -Wpedantic)
endif()

# find dependencies
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(urdf REQUIRED)
find_package(xacro REQUIRED)
find_package(std_msgs REQUIRED)

install(DIRECTORY
  config
  launch
  world
  maps
  rviz
  models
  src
  scripts
  DESTINATION share/${PROJECT_NAME}/
)

install(PROGRAMS
  src/test_action.py
  scripts/waypoint_collector.py
  scripts/experiment_logger.py
  DESTINATION lib/${PROJECT_NAME}
)

install(
  PROGRAMS
  DESTINATION lib/${PROJECT_NAME}
)

ament_package()
